# Generated by Django 2.1.4 on 2018-12-18 16:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=128)),
                ('action_start', models.DateTimeField(default=datetime.datetime(2018, 12, 18, 16, 31, 57, 425669))),
                ('action_end', models.DateTimeField(default=datetime.datetime(2018, 12, 18, 16, 31, 57, 425687))),
            ],
            options={
                'ordering': ['action_start'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128, unique=True)),
                ('open_code', models.CharField(max_length=512)),
                ('close_code', models.CharField(max_length=512)),
                ('registered', models.DateTimeField(default=datetime.datetime(2018, 12, 18, 16, 31, 57, 425006))),
                ('last_seen', models.DateTimeField(default=datetime.datetime(2018, 12, 18, 16, 31, 57, 425029))),
                ('active', models.BooleanField(default=None)),
                ('status', models.CharField(default='close', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.CharField(max_length=200)),
                ('oauth_secret', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnregisteredDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=32)),
                ('joined', models.DateTimeField(default=datetime.datetime(2018, 12, 18, 16, 31, 57, 427284))),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windopen_app.Device', to_field='uuid'),
        ),
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
