# Generated by Django 2.1.4 on 2018-12-18 16:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('windopen_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 18, 16, 35, 25, 394091, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 18, 16, 35, 25, 394070, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 18, 16, 35, 25, 393216, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='device',
            name='registered',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 18, 16, 35, 25, 393195, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='unregistereddevice',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 18, 16, 35, 25, 395830, tzinfo=utc)),
        ),
    ]
