# Generated by Django 2.1.4 on 2018-12-18 16:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('windopen_app', '0002_auto_20181218_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 18, 16, 36, 11, 943079, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 18, 16, 36, 11, 943059, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 18, 16, 36, 11, 942450, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='device',
            name='registered',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 18, 16, 36, 11, 942429, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='unregistereddevice',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 18, 16, 36, 11, 944598, tzinfo=utc)),
        ),
    ]
