# Generated by Django 2.1.4 on 2019-01-09 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('windopen_app', '0005_auto_20181218_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_end',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 9, 11, 12, 12, 155617, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_start',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 9, 11, 12, 12, 155599, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 9, 11, 12, 12, 155064, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='device',
            name='registered',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 9, 11, 12, 12, 155045, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='unregistereddevice',
            name='joined',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 9, 11, 12, 12, 157012, tzinfo=utc)),
        ),
    ]
