# Generated by Django 2.1.4 on 2019-01-09 18:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('windopen_app', '0006_auto_20190109_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_end',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 9, 18, 2, 39, 539747, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_start',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 9, 18, 2, 39, 539726, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 9, 18, 2, 39, 539096, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='device',
            name='registered',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 9, 18, 2, 39, 539074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='unregistereddevice',
            name='joined',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 9, 18, 2, 39, 541330, tzinfo=utc)),
        ),
    ]
