# Generated by Django 2.1.4 on 2019-01-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windopen_app', '0007_auto_20190109_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_end',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='registered',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='unregistereddevice',
            name='joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
